services:
  fastapi:
    build: .
    privileged: true
    dns:
      - 8.8.8.8  # Google Public DNS
      - 8.8.4.4
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge
